# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 17:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
