# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_khan', '0002_auto_20171104_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='slug',
            new_name='ka_slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='tree_slug',
            field=models.CharField(db_index=True, default='000', max_length=256),
            preserve_default=False,
        ),
    ]
