# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_khan', '0003_auto_20171104_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ka_id', models.CharField(db_index=True, max_length=256)),
                ('tree_slug', models.CharField(db_index=True, max_length=256)),
                ('big_file', models.FileField(blank=True, null=True, upload_to='')),
                ('small_file', models.FileField(blank=True, null=True, upload_to='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='get_khan.Topic')),
            ],
        ),
    ]
